### ISSUE TITLE
Gallery with videojs autoplay issue

### ISSUE THREAD

**Issue by ProUnebit** [sachinchoolur/lg-video.js#13]
**Hey! lightgallery is great!**
But a i have a problem...
I use vanilla lightgallery.js in my project for videogallery with videojs. 
From this example http://sachinchoolur.github.io/lightGallery/demos/html5-videos.html#video-without-poster - i created 
similar code, but with lightgallery.js (no jQuery version) and added to options in videojs: true   and  videojsOptions: { autoplay: true}. It's works, but 
every video started in the same time with videojs. In example it works correctly - if i click chosen video exactly this video starts to play and other videos do not play! I need it to work like in the example (very need!!).
No errors in console and ect.
I've tried update lg-video.js and lightgallery core packeges, but this does not change anything!
**What am I doing wrong? I really need your help!**

**Comment by sachinchoolur** [comment]
Closing as duplicate - https://github.com/sachinchoolur/lightgallery.js/issues/184
