### ISSUE TITLE
Use privacy enhanced YouTube embed code

### ISSUE THREAD

**Issue by herrschuessler** [sachinchoolur/lg-video.js#4]
Hi there,

your plugin is currently embedding YouTube videos via the URL `//www.youtube.com/embed/`. Google also offers to embed video via `//www.youtube-nocookie.com/embed/`, which offers some privacy improvements, especially for European countries affected by the GDPR (see https://support.google.com/youtube/answer/171780?hl=en).

Could you simply update the embed URL or add an option to use the privacy enhanced URL? If needed, I could supply a PR.

Thanks

**Comment by sachinchoolur** [comment]
I've added the `youtube-nocookie.com` support. 
Thank you
