### ISSUE TITLE
vimeo has newer version (migrated from froogaloop.js)

### ISSUE THREAD

**Issue by pySilver** [sachinchoolur/lg-video.js#7]
take a loop at https://github.com/vimeo/player.js/blob/master/docs/migrate-from-froogaloop.md

**Comment by garpunkal** [comment]
Hi, any update on this? we're seeing issues in the console with frooglaloop clashing with the new player.

**Comment by sachinchoolur** [comment]
Upgraded to player.js - https://github.com/sachinchoolur/lg-video.js/releases/tag/1.3.0-beta.0

Thank you for your patience
