### ISSUE TITLE
Error with dynamic mode. this.core.items[index].querySelector is not a function

### ISSUE THREAD

**Issue by kotomorda** [sachinchoolur/lg-video.js#9]
Error starting plugin with dynamicEl array. For example:
`lightGallery(document.getElementById('video-gallery'), {
  dynamic: true,
  dynamicEl: [{
    html: "#video",
    poster: "some_img_url"
  }]
});`
where '#video' is the container for the `<video>` element.

An error occurs in the loadVideo function ([Video.prototype.loadVideo](https://github.com/sachinchoolur/lg-video.js/blob/52a883ed922e2f34348658aa173974516a94ab73/src/lg-video.js#L226)) in the line [249](https://github.com/sachinchoolur/lg-video.js/blob/52a883ed922e2f34348658aa173974516a94ab73/src/lg-video.js#L249).
It is probably worth adding the if (!this.core.s.dynamic) condition for the image search logic.

**Comment by Woloja** [comment]
+1... a very strange feature, already fed up with the order, and appeared either on its own, or after the update ...

**Comment by sachinchoolur** [comment]
Thank you for pointing this out. The issue has been fixed in version 1.2.1
